function rfModel = pRFMakeGaussian(fitParams,centerX,centerY,standardDeviation)
% pRFMakeGaussian  Construct a Gaussian RF, using a rectilinear fast path.
%
% The pRFFit setup records one-dimensional axes when stimX/stimY form an
% exact rectilinear grid. The two one-dimensional Gaussians are combined
% with an outer product. Unprepared, nonrectilinear, mixed-class, complex,
% sparse, or degenerate inputs use the general 2-D expression.
%
% pRFv3 implementation by Austin Kuo with Codex.

hasPreparedGrid = isfield(fitParams,'gaussianGrid') && ...
  isstruct(fitParams.gaussianGrid) && isscalar(fitParams.gaussianGrid) && ...
  isfield(fitParams.gaussianGrid,'layout') && ...
  isfield(fitParams.gaussianGrid,'firstAxis') && ...
  isfield(fitParams.gaussianGrid,'secondAxis');
hasFastTypes = isa(fitParams.stimX,'double') && ...
  isa(fitParams.stimY,'double') && isreal(fitParams.stimX) && ...
  isreal(fitParams.stimY) && ~issparse(fitParams.stimX) && ...
  ~issparse(fitParams.stimY) && isa(centerX,'double') && ...
  isa(centerY,'double') && isa(standardDeviation,'double') && ...
  isreal(centerX) && isreal(centerY) && isreal(standardDeviation) && ...
  isscalar(centerX) && isscalar(centerY) && isscalar(standardDeviation) && ...
  isfinite(centerX) && isfinite(centerY) && ...
  isfinite(standardDeviation) && standardDeviation > 0;

if hasPreparedGrid && hasFastTypes
  denominator = 2*(standardDeviation^2);
  % A positive subnormal width can underflow when squared. The full legacy
  % expression then has pointwise Inf/NaN behavior that an outer product
  % cannot reproduce safely, so retain the fallback for that edge case.
  if denominator == 0
    rfModel = exp(-(((fitParams.stimX-centerX).^2)/(2*(standardDeviation^2)) + ...
      ((fitParams.stimY-centerY).^2)/(2*(standardDeviation^2))));
    return
  end
  switch fitParams.gaussianGrid.layout
    case 'ndgrid'
      firstGaussian = exp( ...
        -((fitParams.gaussianGrid.firstAxis-centerX).^2)/denominator);
      secondGaussian = exp( ...
        -((fitParams.gaussianGrid.secondAxis-centerY).^2)/denominator);
    case 'meshgrid'
      firstGaussian = exp( ...
        -((fitParams.gaussianGrid.firstAxis-centerY).^2)/denominator);
      secondGaussian = exp( ...
        -((fitParams.gaussianGrid.secondAxis-centerX).^2)/denominator);
    otherwise
      firstGaussian = [];
      secondGaussian = [];
  end
  if ~isempty(firstGaussian) && ~isempty(secondGaussian)
    rfModel = firstGaussian(:)*secondGaussian(:).';
    return
  end
end

rfModel = exp(-(((fitParams.stimX-centerX).^2)/(2*(standardDeviation^2)) + ...
  ((fitParams.stimY-centerY).^2)/(2*(standardDeviation^2))));
